######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 1 16:03:18 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += /opt/project/hwlib/led
LIBS += -L/opt/project/hwlib/led -lled

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
