######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 30 10:48:54 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += LoginDlg.h
FORMS += LoginDlg.ui
SOURCES += Login.cpp LoginDlg.cpp
