######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 1 15:50:38 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += /opt/project/hwlib/ds18b20
LIBS += -L/opt/project/hwlib/ds18b20 -lds18b20

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
