######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 1 11:31:59 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += /opt/project/hwlib/eeprom
LIBS += -L/opt/project/hwlib/eeprom -leeprom

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
